"""change string length

Revision ID: 53d0fed58ba8
Revises: 01c9afbe8ba6
Create Date: 2023-05-31 21:35:01.867587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53d0fed58ba8'
down_revision = '01c9afbe8ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=300),
               type_=mysql.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
