"""add about_author and profile_pic

Revision ID: 32667491f19c
Revises: dda2fdab9330
Create Date: 2023-05-30 22:19:00.302985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32667491f19c'
down_revision = 'dda2fdab9330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
