"""followers

Revision ID: 9224d6bb8fea
Revises: 53d0fed58ba8
Create Date: 2023-06-04 20:54:30.918694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9224d6bb8fea'
down_revision = '53d0fed58ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
